/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
*/
package DoordeDpackage;



/**
*
* @author ACER
*/
public class Signup extends javax.swing.JFrame {



/**
* Creates new form Signup
*/
public Signup() {
initComponents();
}



/**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
private void initComponents() {



jPasswordField2 = new javax.swing.JPasswordField();
jPasswordField1 = new javax.swing.JPasswordField();
jTextField3 = new javax.swing.JTextField();
jTextField2 = new javax.swing.JTextField();
jTextField1 = new javax.swing.JTextField();
jButton1 = new javax.swing.JButton();
jLabel1 = new javax.swing.JLabel();



setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());



jPasswordField2.setText("jPasswordField2");
jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jPasswordField2ActionPerformed(evt);
}
});
getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 220, 40));



jPasswordField1.setText("jPasswordField1");
getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 220, 40));



jTextField3.setText("Phone Number");
getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 210, 40));



jTextField2.setText("Email");
getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 220, 40));



jTextField1.setText("Fullname");
getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 220, 40));



jButton1.setBackground(new java.awt.Color(191, 46, 46));
jButton1.setForeground(new java.awt.Color(191, 46, 46));
jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoordeDpackage/Signup Buutoon.png"))); // NOI18N
getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 200, 80));



jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DoordeDpackage/iMac - 2 (1).png"))); // NOI18N
getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));



pack();
}// </editor-fold>



private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}



/**
* @param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
if ("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
break;
}
}
} catch (ClassNotFoundException ex) {
java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {
java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {
java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>



/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new Signup().setVisible(true);
}
});
}



// Variables declaration - do not modify
private javax.swing.JButton jButton1;
private javax.swing.JLabel jLabel1;
private javax.swing.JPasswordField jPasswordField1;
private javax.swing.JPasswordField jPasswordField2;
private javax.swing.JTextField jTextField1;
private javax.swing.JTextField jTextField2;
private javax.swing.JTextField jTextField3;
// End of variables declaration
}